[phases.setup]
nixPkgs = ["python311.withPackages (ps: with ps; [ pip setuptools wheel ])"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"