[phases.setup]
nixPkgs = ['python311Full']  # <-- this ensures pip is included

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.start]
cmd = 'uvicorn backend.app.main:app --host 0.0.0.0 --port 8000'
